[package]
name = "parmesan"
version = "0.0.12"
edition = "2018"
description = "PARMESAN: Parallel ARithMEticS on tfhe ENcrypted data."
license = "AGPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "^2.0.0"
rayon = "^1.5.1"
crossbeam-utils = "^0.8.0"
rand = "^0.8.0"
chrono = "^0.4.0"
lazy_static = "^1.4.0"
serde = { version = "^1.0", features = ["derive"] }
serde_yaml = "^0.8"
# this will be needed for publishing (dependency must be an actual crate at crates.io):
# parmesan-concrete-negacyclic = { version = "^0.0.1", features = ["unsafe"] }                        # uses unsafe Rust's PRNG (faster) instead of OpenSSL's one
# concrete can be built from the following fork / branch:
# concrete = { git = "https://github.com/fakub/concrete", branch = "negacyclic", features = ["unsafe"] }
# for local development, clone the repo & checkout to 'negacyclic' branch, and use the following line instead:
concrete = { path = "../concrete-lib/concrete", features = ["unsafe"] }

[features]
default = []                # no feature selected by default
# sequential = []             # run (selected) algorithms sequentially
measure = []                # measure duration of selected operations
log_ops = ["measure"]       # log operation timing into a logfile (used in gnuplot scripts)
