[package]
name = "parmesan"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
concrete = { path = "../concrete-lib/concrete", features = ["unsafe"] }         # uses unsafe Rust's PRNG instead of OpenSSL's one
                                                                                #TODO remove for production !!
